[package]
name = "remote-dev"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
procfs = "0.14.2"
color-eyre = "0.6.2"
